# fly.toml app configuration file generated for jamalbendadi-admin on 2024-01-07T17:55:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jamalbendadi-admin"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[build]

[env]
  DB_CLIENT = "sqlite3"
  DB_FILENAME = "/data/database/data.db"
  FLY_PRIMARY_REGION = "ams"
  PORT = "6055"
  STORAGE_LOCAL_DRIVER = "local"
  STORAGE_LOCAL_ROOT = "/data/uploads"
  STORAGE_LOCATIONS = "local"

[[mounts]]
  source = "data"
  destination = "/data"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 6055
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/server/health"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
